# Generated by Django 3.0.5 on 2020-04-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_p'),
    ]

    operations = [
        migrations.DeleteModel(
            name='p',
        ),
    ]
