# Generated by Django 3.0.5 on 2020-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_delete_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.TextField(null=True),
        ),
    ]
