# Generated by Django 3.0.5 on 2020-04-17 07:11

from django.db import migrations
import json_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_customer_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object'),
        ),
    ]
