# Generated by Django 3.0.5 on 2020-04-17 07:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_auto_20200417_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6),
        ),
    ]
